version: '3'
services:
  myapp:
    image: myapp-image:latest
    build:
      context: .
    container_name: myapp
    ports:
      - "5678:5678"
    volumes:
      - ./data:/app/data
    environment:
      - DB_USERNAME=${DB_USERNAME?error}
      - DB_PASSWORD=${DB_PASSWORD?error}
    networks:
      - myapp-network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD?error}
      - MYSQL_DATABASE=inventory
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
    external: true

volumes:
  mysql:
