name: User story
description: A user story
labels: ["user-story"]
projects: ["AnEventTechInventory/4"]
body:
  - type: input
    id: user-type
    attributes:
      description: As a
      placeholder: user
      validations:
        required: true
  - type: textarea
    id: task
    attributes:
      description: I like to
    validations:
      required: true
