name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Build Software
        run: |
          # Add your build commands here
          # For example:
          make

      - name: Deploy to Remote
        if: success()
        run: |
          # Set up SSH key and known hosts
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ DEPLOY_SERVER }} >> ~/.ssh/known_hosts
            
          # Copy the built software to the remote server
          scp -i ~/.ssh/id_rsa <local_package_path> root@${{ DEPLOY_SERVER }}:~/apiendpoint
          
          # SSH into the remote server and install the software
          ssh -i ~/.ssh/id_rsa root@${ DEPLOY_SERVER } "cd ~/apiendpoint && ./install.sh"
