name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4.1.1

      - name: Build Software
        run: |
          # Build your Go project
          go build -o myapp

      - name: Create ZIP Artifact
        run: |
          # Create a ZIP file from the build output
          zip -r backend.zip myapp

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: software-package
          path: ./backend.zip

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ env.DEPLOY_SERVER }} >> ~/.ssh/known_hosts

      - name: Deploy to Remote
        run: |
          # Copy the ZIP artifact to the remote server
          scp -i ~/.ssh/id_rsa ./backend.zip user@${{ env.DEPLOY_SERVER }}:~/backend

          # SSH into the remote server and extract the ZIP file
          ssh -i ~/.ssh/id_rsa user@${{ env.DEPLOY_SERVER }} "cd ~/backend && unzip -o backend.zip && ./install.sh"
