name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4.1.1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.3  # Use the version you need

      - name: Build Software for arm64
        env:
          GOARCH: arm64
          GOARM: 7
        run: |
          go build -o myapp src/main.go

      - name: Create Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM alpine:latest
          WORKDIR /app
          COPY myapp /app/
          EXPOSE 8080
          CMD ["/app/myapp"]
          EOF
        shell: bash

      - name: Build Docker Image
        run: |
          docker build -t myapp-image .

      - name: Save Docker Image as Tarball
        run: |
          docker save -o myapp-image.tar myapp-image

      - name: Upload Docker Image to Remote Server
        run: |
          scp myapp-image.tar user@${{ secrets.DEPLOY_SERVER }}:~/myapp-image.tar

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.DEPLOY_SERVER }} >> ~/.ssh/known_hosts

      - name: Deploy on Remote Server
        run: |
          # SSH into the remote server and remove the old container if it exists
          ssh -i ~/.ssh/id_rsa user@${{ secrets.DEPLOY_SERVER }} "docker rm -f myapp-container || true"

          # Load the new Docker image
          ssh -i ~/.ssh/id_rsa user@${{ secrets.DEPLOY_SERVER }} "docker load -i ~/myapp-image.tar"

          # Run the Docker container with the new image on the remote server
          ssh -i ~/.ssh/id_rsa user@${{ secrets.DEPLOY_SERVER }} "docker run -d -p 8080:8080 --name myapp-container myapp-image"
