name: Pull Request Check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.3

      - name: Run Tests
        run: go test ./...

  build:
    name: Build for ARM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.3

      - name: Build Application for ARM
        run: |
          export GIN_MODE=release
          env GOARCH=arm go build -o myapp
